import type { PosCatalog, PromotionDef } from "@/lib/types";

const img = (id: number) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200`;

const HOTDOG_MODS = [
  { id: "mod_cheese", name: "Qo‘shimcha pishloq", price: 3000, groupName: "Qo‘shimchalar", maxQty: 3 },
  { id: "mod_jalapeno", name: "Xalapenyo", price: 2000, groupName: "Qo‘shimchalar", maxQty: 3 },
  { id: "mod_bacon", name: "Bekon", price: 6000, groupName: "Qo‘shimchalar", maxQty: 2 },
  { id: "mod_onion", name: "Qovurilgan piyoz", price: 2000, groupName: "Qo‘shimchalar", maxQty: 2 },
  { id: "mod_mushroom", name: "Qo‘ziqorin", price: 3000, groupName: "Qo‘shimchalar", maxQty: 2 },
  { id: "mod_sauce", name: "Ekstra sous", price: 2000, groupName: "Souslar", maxQty: 4 },
];

const DRINK_MODS = [
  { id: "mod_ice", name: "Muz qo‘shish", price: 0, groupName: "Ichimlik", maxQty: 1 },
  { id: "mod_lemon", name: "Limon", price: 1000, groupName: "Ichimlik", maxQty: 2 },
];

/**
 * Development-only stand-in for the real VIBE POS SQLite database.
 * Used when POS_MODE=mock. Production always reads the live POS through the
 * local bridge agent, so prices/stock/promos stay authoritative.
 */
export function buildMockCatalog(): PosCatalog {
  return {
    version: `mock-${new Date().toISOString().slice(0, 13)}`,
    source: "mock",
    currency: "UZS",
    generatedAt: new Date().toISOString(),
    categories: [
      { id: "cat_hotdog", name: "Hotdoglar", emoji: "🌭", sortOrder: 1 },
      { id: "cat_burger", name: "Burgerlar", emoji: "🍔", sortOrder: 2 },
      { id: "cat_drink", name: "Ichimliklar", emoji: "🥤", sortOrder: 3 },
      { id: "cat_extra", name: "Qo‘shimchalar", emoji: "🍟", sortOrder: 4 },
      { id: "cat_combo", name: "Kombolar", emoji: "🎁", sortOrder: 5 },
    ],
    products: [
      {
        id: "hd_classic",
        categoryId: "cat_hotdog",
        name: "VIBE Classic hotdog",
        description: "Mol go‘shtli sosiska, taze non, ketchup, mayonez, tuzlangan bodring",
        price: 22000,
        imageUrl: img(5584279),
        isAvailable: true,
        stock: 40,
        modifiers: HOTDOG_MODS,
        tags: ["popular"],
      },
      {
        id: "hd_cheese",
        categoryId: "cat_hotdog",
        name: "Cheese hotdog",
        description: "Ikki xil pishloq, sarimsoqli sous, qovurilgan piyoz",
        price: 27000,
        imageUrl: img(38004079),
        isAvailable: true,
        stock: 32,
        modifiers: HOTDOG_MODS,
        tags: ["popular"],
      },
      {
        id: "hd_spicy",
        categoryId: "cat_hotdog",
        name: "Spicy hotdog",
        description: "Achchiq sosiska, xalapenyo, chipotle sous",
        price: 28000,
        imageUrl: img(37098337),
        isAvailable: true,
        stock: 18,
        modifiers: HOTDOG_MODS,
        tags: ["spicy"],
      },
      {
        id: "hd_footlong",
        categoryId: "cat_hotdog",
        name: "Footlong hotdog",
        description: "Uzun sosiska, ko‘p sous, katta non",
        price: 34000,
        imageUrl: img(2204769),
        isAvailable: true,
        stock: 12,
        modifiers: HOTDOG_MODS,
      },
      {
        id: "bg_vibe",
        categoryId: "cat_burger",
        name: "VIBE Burger",
        description: "200 g mol go‘sht kotleti, cheddar, salat, pomidor, VIBE sous",
        price: 39000,
        imageUrl: img(19247557),
        isAvailable: true,
        stock: 25,
        modifiers: HOTDOG_MODS,
        tags: ["popular"],
      },
      {
        id: "bg_double",
        categoryId: "cat_burger",
        name: "Double Cheese Burger",
        description: "Ikki kotlet, ikki pishloq, karam sous",
        price: 55000,
        imageUrl: img(38896821),
        isAvailable: true,
        stock: 15,
        modifiers: HOTDOG_MODS,
      },
      {
        id: "bg_chicken",
        categoryId: "cat_burger",
        name: "Crispy Chicken Burger",
        description: "Xrustashka tovuq, achchiq-mayonez sous, salat",
        price: 35000,
        imageUrl: img(34466111),
        isAvailable: true,
        stock: 9,
        modifiers: HOTDOG_MODS,
      },
      {
        id: "dr_cola",
        categoryId: "cat_drink",
        name: "Cola 0.5",
        description: "Sovutilgan gazlangan ichimlik",
        price: 9000,
        imageUrl: img(12944766),
        isAvailable: true,
        stock: 120,
        modifiers: DRINK_MODS,
      },
      {
        id: "dr_lemonade",
        categoryId: "cat_drink",
        name: "Uy limonadi 0.4",
        description: "Limon, na’matak, yalpiz",
        price: 14000,
        imageUrl: img(12944766),
        isAvailable: true,
        stock: 60,
        modifiers: DRINK_MODS,
        tags: ["new"],
      },
      {
        id: "dr_water",
        categoryId: "cat_drink",
        name: "Suv 0.5",
        description: "Sovutilgan ichimlik suvi",
        price: 4000,
        isAvailable: true,
        stock: 200,
        modifiers: [],
      },
      {
        id: "ex_fries",
        categoryId: "cat_extra",
        name: "Fri kartoshka",
        description: "Tuz va paprika qo‘shilgan",
        price: 15000,
        isAvailable: true,
        stock: 70,
        modifiers: [{ id: "mod_cheese_sauce", name: "Pishloqli sous", price: 4000, maxQty: 2 }],
      },
      {
        id: "ex_nuggets",
        categoryId: "cat_extra",
        name: "Nuggets 6 dona",
        description: "Tovuq nuggetsi, sous tanlanadi",
        price: 19000,
        isAvailable: true,
        stock: 44,
        modifiers: [{ id: "mod_sauce", name: "Ekstra sous", price: 2000, maxQty: 3 }],
      },
      {
        id: "cb_hotdog_combo",
        categoryId: "cat_combo",
        name: "Hotdog + Fri + Cola",
        description: "Classic hotdog, fri kartoshka va Cola 0.5",
        price: 42000,
        oldPrice: 46000,
        isAvailable: true,
        stock: 30,
        modifiers: HOTDOG_MODS,
        tags: ["combo"],
      },
      {
        id: "cb_burger_combo",
        categoryId: "cat_combo",
        name: "Burger + Fri + Cola",
        description: "VIBE Burger, fri kartoshka va Cola 0.5",
        price: 58000,
        oldPrice: 63000,
        isAvailable: true,
        stock: 20,
        modifiers: HOTDOG_MODS,
        tags: ["combo"],
      },
    ],
    settings: {
      brandName: "VIBE — HotDog · Burger · Drinks",
      currency: "UZS",
      deliveryEnabled: true,
      pickupEnabled: true,
      dineInEnabled: true,
      deliveryFee: 12000,
      freeDeliveryFrom: 150000,
      minOrderAmount: 30000,
      prepMinutes: 15,
      deliveryMinutes: 25,
      paymentMethods: [
        { id: "cash", label: "Naqd pul", hint: "Yetkazib beruvchi bilan naqd", enabled: true, requiresOnline: false },
        { id: "card_transfer", label: "Karta o‘tkazma", hint: "Karta raqamiga o‘tkazma", enabled: true, requiresOnline: false },
        { id: "terminal", label: "Bank terminal", hint: "Kuryer terminalida karta", enabled: true, requiresOnline: false },
        { id: "mixed", label: "Aralash to‘lov", hint: "Qismen naqd, qismen karta", enabled: true, requiresOnline: false },
        { id: "online", label: "Online to‘lov", hint: "Ilova ichida to‘lov", enabled: false, requiresOnline: true },
      ],
      workHours: { open: "10:00", close: "23:30" },
      address: "Toshkent, Chilonzor 9-kvartal, VIBE",
      phone: "+998 90 000 00 00",
      location: { lat: 41.2755, lng: 69.2075 },
    },
  };
}

export function buildMockPromotions(): PromotionDef[] {
  const now = new Date();
  const in30Days = new Date(now.getTime() + 30 * 24 * 3600 * 1000).toISOString();
  return [
    {
      code: "4PLUS1",
      title: "4+1 doimiy mijozlarga",
      description: "Har 5 ta hotdogdan 1 tasi bepul. Telefon raqami tasdiqlangan doimiy mijozlar uchun.",
      type: "FOUR_PLUS_ONE",
      eligibleCategoryIds: ["cat_hotdog"],
      eligibleProductIds: [],
      minQty: 4,
      requiresPhone: true,
      requiresHistory: true,
      maxUsesPerCustomer: 5,
      activeFrom: null,
      activeUntil: null,
      enabled: true,
      priority: 100,
    },
    {
      code: "OPENING_2PLUS1",
      title: "Ochilish 2+1 burger",
      description: "Har 3 ta burgerdan 1 tasi bepul — ochilish aksiyasi.",
      type: "TWO_PLUS_ONE",
      eligibleCategoryIds: ["cat_burger"],
      eligibleProductIds: [],
      minQty: 2,
      requiresPhone: false,
      requiresHistory: false,
      maxUsesPerCustomer: 1,
      activeFrom: null,
      activeUntil: in30Days,
      enabled: true,
      priority: 90,
    },
    {
      code: "VIBE10",
      title: "Kombolarga 10%",
      description: "Kambo buyurtmalariga 10% chegirma.",
      type: "PERCENT",
      eligibleCategoryIds: ["cat_combo"],
      eligibleProductIds: [],
      minQty: 1,
      discountPercent: 10,
      requiresPhone: false,
      requiresHistory: false,
      maxUsesPerCustomer: null,
      activeFrom: null,
      activeUntil: null,
      enabled: true,
      priority: 50,
    },
  ];
}
